services:
  kodus-service-analytics:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - log_volume:/app/logs
    logging:
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - "3007:3007"
    environment:
      - ENV=production
      - NODE_ENV=production
    env_file:
      - .env.qa
    networks:
      - shared-network
    restart: unless-stopped

volumes:
  log_volume:

networks:
  shared-network:
    external: true 