services:
  kodus-service-analytics:
    image: ${IMAGE_NAME_PROD}
    container_name: ${CONTAINER_NAME}
    volumes:
      - log_volume:/app/logs
      - ./google-credentials.json:/app/dist/config/google-credentials.json
    logging:
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - "3008:3008"
    environment:
      - ENV=production
      - NODE_ENV=production
    env_file:
      - .env.prod
    networks:
      - shared-network
    restart: unless-stopped

volumes:
  log_volume:

networks:
  shared-network:
    external: true 