services:
  kodus-service-analytics:
    image: ${IMAGE_NAME_PROD}
    container_name: ${CONTAINER_NAME}
    volumes:
      - log_volume:/app/logs
    logging:
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ENV=production
      - NODE_ENV=production
    env_file:
      - .env.prod
    networks:
      - shared-network
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerFiles/Dockerfile.prod

volumes:
  log_volume:

networks:
  shared-network:
    external: true 